views:
    directory: "./../views/"

routes:
    test:
        url: "/MiniFrameworkPhp/"
        method: "GET"
        action: "\KB\DemoBundle\Controllers\DemoController::indexAction"

pdo:
    server: 172.16.1.127
    user: root
    password: ~

logger:
    filelogger:
        fullpathname: ./../error.log