views:
    directory: /views/

routes:
    demoBundle:
        url: /MiniFrameworkPhp/
        method: GET
        action: \KB\DemoBundle\Controllers\DemoController::indexAction

pdo:
    server: localhost
    user: root
    password: ~

logger:
    filelogger:
        pathname: /error.log