views:
    directory: /views/

routes:
    demoBundle:
        url: /
        method: GET
        action: \KB\DemoBundle\Controllers\DemoController::indexAction

doctrine:
    default:
        host: localhost
        user: root
        password: root
        dbname: demo
        driver: pdo_mysql

logger:
    filelogger:
        pathname: /error.log