views:
    directory: /views/

routes: ~

doctrine:
    default:
        host:       localhost
        user:       root
        password:   root
        dbname:     ~
        driver:     pdo_mysql

logger:
    filelogger:
        pathname: /error.log